### ISSUE TITLE
Wingrind does not understand compressed file and function names

### ISSUE THREAD

**Issue by derickr** [ceefour/wincachegrind#1]
Xdebug 2.3 has implemented file and function name compression as per the specs at http://valgrind.org/docs/manual/cl-format.html#cl-format.overview.compression1

The Xdebug issue for this is http://bugs.xdebug.org/view.php?id=1054 and PR #154 is at https://github.com/xdebug/xdebug/pull/154

As this changes created cachegrind files, Wincachegrind needs to add support for this. This had been reported as an issue on the Xdebug issue tracker at http://bugs.xdebug.org/view.php?id=1115

**Comment by ceefour** [comment]
I am no longer maintaining this.

Feel free to pull request.

**Comment by ceefour** [comment]
@derickr can you give me a sample _but simple_ `cachegrind.out` file to test this functionality?

**Comment by bramstroker** [comment]
@ceefour, I'm also having issues importing Xdebug 2.3.2 files. Here is a sample cachegrind file.

https://drive.google.com/open?id=0B1elTQ9jckuHQXc0clF3djBRc0U&authuser=0

**Comment by derickr** [comment]
@ceefour https://github.com/derickr/xdebug/blob/master/tests/bug00631.phpt
